# Generated by Django 5.1.11 on 2025-08-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('slug', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.chapter')),
            ],
            options={
                'ordering': ['chapter__order', 'order'],
                'unique_together': {('chapter', 'slug')},
            },
        ),
    ]
