# Generated by Django 5.1.11 on 2025-08-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='test_runner',
            field=models.TextField(blank=True),
        ),
    ]
