# Generated by Django 5.1.11 on 2025-10-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_test_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='book_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
