# Generated by Django 5.1.11 on 2025-10-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_chapter_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
