# Generated by Django 5.1.11 on 2025-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_difficulty_assignment_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
