# Generated by Django 5.1.11 on 2025-10-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Users can see this assignment only after this time', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
    ]
