# Generated by Django 5.1.11 on 2025-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_chapter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='publish_until',
            field=models.DateTimeField(blank=True, help_text='Users cannot see this assignment after this time', null=True),
        ),
    ]
