# Generated by Django 5.1.11 on 2025-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_assignment_publish_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
    ]
