# Generated by Django 5.1.11 on 2025-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Python 2025', max_length=200)),
                ('site_tagline', models.CharField(blank=True, max_length=255)),
                ('footer_text', models.TextField(blank=True)),
                ('copyright_text', models.CharField(default='© Python-2025', max_length=255)),
            ],
        ),
    ]
