# Generated by Django 5.1.11 on 2025-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedata',
            options={'verbose_name': 'Site Data', 'verbose_name_plural': 'Site Data'},
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='site_name',
            field=models.CharField(default='Python Programming - WiSe 2024-2025', max_length=200),
        ),
    ]
