# Generated by Django 5.1.11 on 2025-11-12 16:45

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0002_alter_sitedata_options_alter_sitedata_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Homepage Title', max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.AddField(
            model_name='sitedata',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='name',
            field=models.CharField(blank=True, help_text='Site owner or contact person', max_length=100),
        ),
    ]
