# Generated by Django 5.1.11 on 2025-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='run_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('error', 'error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='run_stderr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='run_stdout',
            field=models.TextField(blank=True),
        ),
    ]
