# Generated by Django 5.1.11 on 2025-08-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_submission_run_status_submission_run_stderr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='run_stderr',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='run_stdout',
        ),
    ]
