# Generated by Django 5.1.11 on 2025-08-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_remove_submission_run_stderr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
