# Generated by Django 5.1.11 on 2025-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_submission_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
